server:
  port: 8083


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=UTF-8
  mvc:
    #    static-path-pattern: /**
    view:
      prefix: /
      suffix: .html
  #  resources:
  #    static-locations:
  #      - classpath:/templates/
  #      - classpath:/static/
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/static/
    suffix: .html

